### ISSUE TITLE
Add support for multiple concurrent versions of circleci builder

### ISSUE THREAD

**Issue by badrange** [wunderio/silta-circleci#126]
This issue is created as a follow up of #124 - one goal is to be able to create projects running on PHP 7.4 while supporting legacy 7.3 based projects.

**Comment by Jancis** [comment]
We created multiple circleci images with different tags now. You can use custom executor and define an circleci builder image like so: https://github.com/wunderio/drupal-project-k8s/commit/86343276655d8dbfc861706fc13232337d293651

```
executors:
  cicd74:
    docker:
      - image: eu.gcr.io/silta-images/cicd:circleci-php7.4-node14-composer1-v0.1
      
workflows:
  commit:
    jobs:
      - silta/drupal-build-deploy: &build-deploy
          (..)
          executor: cicd74
```

And use PHP 7.4 for php-fpm and shell versions in drupal chart like so: https://github.com/wunderio/drupal-project-k8s/commit/169e0c6590f7c782515a0a20efb50bfbf0a279bf
(just remember to use `php:7.4-fpm-v0.1` and `shell:7.4-v0.1` instead)

Here's a list of images available currently: 
 - CircleCI: https://console.cloud.google.com/gcr/images/silta-images/EU/cicd
 - PHP: https://console.cloud.google.com/gcr/images/silta-images/EU/php
 - Shell: https://console.cloud.google.com/gcr/images/silta-images/EU/shell
