### ISSUE TITLE
Custom drupal directory but silta in root

### ISSUE THREAD

**Issue by badrange** [wunderio/silta-circleci#146]
In our project we have a lot of services in addition to drupal, so it would be great to place drupal in it's own subdirectory to keep each service isolated. 

I tried to move all drupal related files to /drupal, while keeping silta in the root of the project. 

This setup is not supported by drupal-validate nor drupal-deploy, they will be looking for silta files in drupal/silta. Is this something you would be interested in changing?

**Comment by Jancis** [comment]
A quick workaround could be changing working directory with a custom codebase-build step? I'm just guessing, this might not work -
https://github.com/wunderio/silta-circleci/blob/master/orb/jobs/%40drupal.yml#L146

```
codebase-build:
  - run:
      name: Build local helm chart
      command: cd ./subdirectory
```
